# Generated by Django 2.2.2 on 2021-02-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tabla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_registro', models.DateTimeField()),
            ],
        ),
    ]
